export const INITIAL_CPT_EXCEL = [
    {
        id: 1,
        title: "Test 1: Department Budget Analysis",
        type: 'Excel',
        isFree: true,
        instructions: "Complete all 10 tasks: Enter data in columns C & D, and type formulas in the specified colored cells",
        data: [
            { id: 1, name: "Department", val1: "Budget (Lakhs)", val2: "" },
            { id: 2, name: "Education", val1: "450", val2: "" },
            { id: 3, name: "Health", val1: "320", val2: "" },
            { id: 4, name: "Transport", val1: "280", val2: "" },
            { id: 5, name: "Agriculture", val1: "195", val2: "" },
            { id: 6, name: "Defense", val1: "510", val2: "" },
            { id: 7, name: "Infrastructure", val1: "375", val2: "" },
            { id: 8, name: "Social Welfare", val1: "225", val2: "" },
            { id: 9, name: "IT & Telecom", val1: "165", val2: "" },
            { id: 10, name: "Sports", val1: "80", val2: "" },
        ],
        tasks: [
            { id: 1, text: "Task 1: Copy column A data to column C", marks: 2 },
            { id: 2, text: "Task 2: Copy column B data to column D", marks: 2 },
            { id: 3, text: "Task 3: Calculate TOTAL budget using SUM formula in D11", marks: 2 },
            { id: 4, text: "Task 4: Calculate AVERAGE budget using AVERAGE formula in D12", marks: 2 },
            { id: 5, text: "Task 5: Calculate MAX budget using MAX formula in D13", marks: 2 },
            { id: 6, text: "Task 6: Calculate MIN budget using MIN formula in D14", marks: 2 },
            { id: 7, text: "Task 7: COUNT departments using COUNT formula in D15", marks: 2 },
            { id: 8, text: "Task 8: Calculate Education percentage: (D2/D11)*100 in E2", marks: 2 },
            { id: 9, text: "Task 9: Apply BOLD formatting to row 1 (headers)", marks: 2 },
            { id: 10, text: "Task 10: Apply CENTER alignment to column headers", marks: 2 },
        ]
    },
    {
        id: 2,
        title: "Test 2: Sales Data Analysis",
        type: 'Excel',
        instructions: "Complete all tasks: Copy data to C & D columns and apply formulas for sales calculations",
        data: [
            { id: 1, name: "Product", val1: "Sales (Units)", val2: "" },
            { id: 2, name: "Laptop", val1: "125", val2: "" },
            { id: 3, name: "Desktop", val1: "89", val2: "" },
            { id: 4, name: "Printer", val1: "234", val2: "" },
            { id: 5, name: "Scanner", val1: "67", val2: "" },
            { id: 6, name: "Tablet", val1: "312", val2: "" },
            { id: 7, name: "Mobile", val1: "567", val2: "" },
            { id: 8, name: "Keyboard", val1: "445", val2: "" },
            { id: 9, name: "Mouse", val1: "398", val2: "" },
            { id: 10, name: "Monitor", val1: "156", val2: "" },
        ],
        tasks: [
            { id: 1, text: "Task 1: Type column A (Product names) into column C", marks: 2 },
            { id: 2, text: "Task 2: Type column B (Sales Units) into column D", marks: 2 },
            { id: 3, text: "Task 3: Total sales: =SUM(D2:D10) in D11", marks: 2 },
            { id: 4, text: "Task 4: Average sales: =AVERAGE(D2:D10) in D12", marks: 2 },
            { id: 5, text: "Task 5: Highest sales: =MAX(D2:D10) in D13", marks: 2 },
            { id: 6, text: "Task 6: Lowest sales: =MIN(D2:D10) in D14", marks: 2 },
            { id: 7, text: "Task 7: Product count: =COUNT(D2:D10) in D15", marks: 2 },
            { id: 8, text: "Task 8: Mobile percentage: =(D7/D11)*100 in E7", marks: 2 },
            { id: 9, text: "Task 9: Bold formatting for header row", marks: 2 },
            { id: 10, text: "Task 10: Right align all numerical data", marks: 2 },
        ]
    },
    {
        id: 3,
        title: "Test 3: Student Marks Sheet",
        type: 'Excel',
        instructions: "Enter student data and calculate statistics using Excel formulas",
        data: [
            { id: 1, name: "Student Name", val1: "Marks (out of 100)", val2: "" },
            { id: 2, name: "Rahul", val1: "85", val2: "" },
            { id: 3, name: "Priya", val1: "92", val2: "" },
            { id: 4, name: "Amit", val1: "78", val2: "" },
            { id: 5, name: "Sneha", val1: "88", val2: "" },
            { id: 6, name: "Vikram", val1: "95", val2: "" },
            { id: 7, name: "Meera", val1: "81", val2: "" },
            { id: 8, name: "Arjun", val1: "73", val2: "" },
            { id: 9, name: "Kavita", val1: "90", val2: "" },
            { id: 10, name: "Rohan", val1: "87", val2: "" },
        ],
        tasks: [
            { id: 1, text: "Task 1: Copy student names to column C", marks: 2 },
            { id: 2, text: "Task 2: Copy marks to column D", marks: 2 },
            { id: 3, text: "Task 3: Total marks: =SUM(D2:D10) in D11", marks: 2 },
            { id: 4, text: "Task 4: Class average: =AVERAGE(D2:D10) in D12", marks: 2 },
            { id: 5, text: "Task 5: Highest marks: =MAX(D2:D10) in D13", marks: 2 },
            { id: 6, text: "Task 6: Lowest marks: =MIN(D2:D10) in D14", marks: 2 },
            { id: 7, text: "Task 7: Student count: =COUNT(D2:D10) in D15", marks: 2 },
            { id: 8, text: "Task 8: Vikram's percentage: =(D6/100)*100 in E6", marks: 2 },
            { id: 9, text: "Task 9: Bold and color header row (light blue)", marks: 2 },
            { id: 10, text: "Task 10: Add borders to all filled cells", marks: 2 },
        ]
    },
    {
        id: 4,
        title: "Test 4: Employee Salary Report",
        type: 'Excel',
        instructions: "Type employee data and calculate salary statistics",
        data: [
            { id: 1, name: "Employee", val1: "Salary (₹)", val2: "" },
            { id: 2, name: "Rajesh Kumar", val1: "45000", val2: "" },
            { id: 3, name: "Sunita Sharma", val1: "52000", val2: "" },
            { id: 4, name: "Anil Verma", val1: "38000", val2: "" },
            { id: 5, name: "Pooja Singh", val1: "48000", val2: "" },
            { id: 6, name: "Manoj Gupta", val1: "55000", val2: "" },
            { id: 7, name: "Ritu Patel", val1: "42000", val2: "" },
            { id: 8, name: "Deepak Yadav", val1: "39000", val2: "" },
            { id: 9, name: "Neha Jain", val1: "51000", val2: "" },
            { id: 10, name: "Suresh Meena", val1: "46000", val2: "" },
        ],
        tasks: [
            { id: 1, text: "Task 1: Enter employee names in column C", marks: 2 },
            { id: 2, text: "Task 2: Enter salary data in column D", marks: 2 },
            { id: 3, text: "Task 3: Total payroll: =SUM(D2:D10) in D11", marks: 2 },
            { id: 4, text: "Task 4: Average salary: =AVERAGE(D2:D10) in D12", marks: 2 },
            { id: 5, text: "Task 5: Maximum salary: =MAX(D2:D10) in D13", marks: 2 },
            { id: 6, text: "Task 6: Minimum salary: =MIN(D2:D10) in D14", marks: 2 },
            { id: 7, text: "Task 7: Employee count: =COUNT(D2:D10) in D15", marks: 2 },
            { id: 8, text: "Task 8: Manoj's salary %: =(D6/D11)*100 in E6", marks: 2 },
            { id: 9, text: "Task 9: Apply currency format (₹) to all salary cells", marks: 2 },
            { id: 10, text: "Task 10: Center align headers and bold them", marks: 2 },
        ]
    },
    {
        id: 5,
        title: "Test 5: Monthly Expenses Tracker",
        type: 'Excel',
        instructions: "Record expense data and calculate monthly statistics",
        data: [
            { id: 1, name: "Expense Type", val1: "Amount (₹)", val2: "" },
            { id: 2, name: "Rent", val1: "12000", val2: "" },
            { id: 3, name: "Groceries", val1: "5500", val2: "" },
            { id: 4, name: "Electricity", val1: "1800", val2: "" },
            { id: 5, name: "Water", val1: "600", val2: "" },
            { id: 6, name: "Internet", val1: "899", val2: "" },
            { id: 7, name: "Transportation", val1: "3200", val2: "" },
            { id: 8, name: "Entertainment", val1: "2500", val2: "" },
            { id: 9, name: "Medical", val1: "1500", val2: "" },
            { id: 10, name: "Miscellaneous", val1: "2000", val2: "" },
        ],
        tasks: [
            { id: 1, text: "Task 1: Type expense categories in column C", marks: 2 },
            { id: 2, text: "Task 2: Type amounts in column D", marks: 2 },
            { id: 3, text: "Task 3: Total expenses: =SUM(D2:D10) in D11", marks: 2 },
            { id: 4, text: "Task 4: Average expense: =AVERAGE(D2:D10) in D12", marks: 2 },
            { id: 5, text: "Task 5: Highest expense: =MAX(D2:D10) in D13", marks: 2 },
            { id: 6, text: "Task 6: Lowest expense: =MIN(D2:D10) in D14", marks: 2 },
            { id: 7, text: "Task 7: Expense items: =COUNT(D2:D10) in D15", marks: 2 },
            { id: 8, text: "Task 8: Rent percentage: =(D2/D11)*100 in E2", marks: 2 },
            { id: 9, text: "Task 9: Highlight highest expense in yellow", marks: 2 },
            { id: 10, text: "Task 10: Apply number formatting with comma separator", marks: 2 },
        ]
    },
    {
        id: 6,
        title: "Test 6: Inventory Stock Report",
        type: 'Excel',
        instructions: "Manage inventory data with formula calculations",
        data: [
            { id: 1, name: "Item Name", val1: "Quantity", val2: "" },
            { id: 2, name: "Notebooks", val1: "450", val2: "" },
            { id: 3, name: "Pens", val1: "1200", val2: "" },
            { id: 4, name: "Pencils", val1: "800", val2: "" },
            { id: 5, name: "Erasers", val1: "600", val2: "" },
            { id: 6, name: "Rulers", val1: "350", val2: "" },
            { id: 7, name: "Markers", val1: "275", val2: "" },
            { id: 8, name: "Files", val1: "520", val2: "" },
            { id: 9, name: "Staplers", val1: "180", val2: "" },
            { id: 10, name: "Clips", val1: "950", val2: "" },
        ],
        tasks: [
            { id: 1, text: "Task 1: Copy item names to column C", marks: 2 },
            { id: 2, text: "Task 2: Copy quantities to column D", marks: 2 },
            { id: 3, text: "Task 3: Total stock: =SUM(D2:D10) in D11", marks: 2 },
            { id: 4, text: "Task 4: Average quantity: =AVERAGE(D2:D10) in D12", marks: 2 },
            { id: 5, text: "Task 5: Maximum stock: =MAX(D2:D10) in D13", marks: 2 },
            { id: 6, text: "Task 6: Minimum stock: =MIN(D2:D10) in D14", marks: 2 },
            { id: 7, text: "Task 7: Item count: =COUNT(D2:D10) in D15", marks: 2 },
            { id: 8, text: "Task 8: Pens percentage: =(D3/D11)*100 in E3", marks: 2 },
            { id: 9, text: "Task 9: Add alternating row colors (light grey)", marks: 2 },
            { id: 10, text: "Task 10: Freeze header row for scrolling", marks: 2 },
        ]
    },
    {
        id: 7,
        title: "Test 7: Exam Results Summary",
        type: 'Excel',
        instructions: "Calculate exam statistics and subject-wise analysis",
        data: [
            { id: 1, name: "Subject", val1: "Total Marks", val2: "" },
            { id: 2, name: "Hindi", val1: "87", val2: "" },
            { id: 3, name: "English", val1: "92", val2: "" },
            { id: 4, name: "Mathematics", val1: "78", val2: "" },
            { id: 5, name: "Science", val1: "85", val2: "" },
            { id: 6, name: "Social Studies", val1: "90", val2: "" },
            { id: 7, name: "Computer", val1: "95", val2: "" },
            { id: 8, name: "Physical Education", val1: "88", val2: "" },
            { id: 9, name: "Drawing", val1: "82", val2: "" },
            { id: 10, name: "Music", val1: "80", val2: "" },
        ],
        tasks: [
            { id: 1, text: "Task 1: Enter subject names in column C", marks: 2 },
            { id: 2, text: "Task 2: Enter marks in column D", marks: 2 },
            { id: 3, text: "Task 3: Total marks: =SUM(D2:D10) in D11", marks: 2 },
            { id: 4, text: "Task 4: Average marks: =AVERAGE(D2:D10) in D12", marks: 2 },
            { id: 5, text: "Task 5: Best subject: =MAX(D2:D10) in D13", marks: 2 },
            { id: 6, text: "Task 6: Weakest subject: =MIN(D2:D10) in D14", marks: 2 },
            { id: 7, text: "Task 7: Subject count: =COUNT(D2:D10) in D15", marks: 2 },
            { id: 8, text: "Task 8: Computer %: =(D7/900)*100 in E7", marks: 2 },
            { id: 9, text: "Task 9: Color code: Green if >85, Red if <80", marks: 2 },
            { id: 10, text: "Task 10: Add chart title 'Academic Performance'", marks: 2 },
        ]
    },
    {
        id: 8,
        title: "Test 8: Project Timeline Budget",
        type: 'Excel',
        instructions: "Track project phases and calculate budget allocations",
        data: [
            { id: 1, name: "Project Phase", val1: "Budget (Lakhs)", val2: "" },
            { id: 2, name: "Planning", val1: "15", val2: "" },
            { id: 3, name: "Design", val1: "25", val2: "" },
            { id: 4, name: "Development", val1: "80", val2: "" },
            { id: 5, name: "Testing", val1: "35", val2: "" },
            { id: 6, name: "Deployment", val1: "20", val2: "" },
            { id: 7, name: "Training", val1: "12", val2: "" },
            { id: 8, name: "Documentation", val1: "8", val2: "" },
            { id: 9, name: "Support", val1: "18", val2: "" },
            { id: 10, name: "Maintenance", val1: "22", val2: "" },
        ],
        tasks: [
            { id: 1, text: "Task 1: Type project phases in column C", marks: 2 },
            { id: 2, text: "Task 2: Type budget values in column D", marks: 2 },
            { id: 3, text: "Task 3: Total project cost: =SUM(D2:D10) in D11", marks: 2 },
            { id: 4, text: "Task 4: Average phase cost: =AVERAGE(D2:D10) in D12", marks: 2 },
            { id: 5, text: "Task 5: Costliest phase: =MAX(D2:D10) in D13", marks: 2 },
            { id: 6, text: "Task 6: Cheapest phase: =MIN(D2:D10) in D14", marks: 2 },
            { id: 7, text: "Task 7: Phase count: =COUNT(D2:D10) in D15", marks: 2 },
            { id: 8, text: "Task 8: Development %: =(D4/D11)*100 in E4", marks: 2 },
            { id: 9, text: "Task 9: Merge cells A1:B1 for title", marks: 2 },
            { id: 10, text: "Task 10: Apply table format with borders", marks: 2 },
        ]
    },
    {
        id: 9,
        title: "Test 9: Population Census Data",
        type: 'Excel',
        instructions: "Analyze district-wise population statistics",
        data: [
            { id: 1, name: "District", val1: "Population (Lakhs)", val2: "" },
            { id: 2, name: "Jaipur", val1: "66.26", val2: "" },
            { id: 3, name: "Jodhpur", val1: "36.87", val2: "" },
            { id: 4, name: "Udaipur", val1: "30.68", val2: "" },
            { id: 5, name: "Kota", val1: "19.51", val2: "" },
            { id: 6, name: "Bikaner", val1: "23.64", val2: "" },
            { id: 7, name: "Ajmer", val1: "25.84", val2: "" },
            { id: 8, name: "Alwar", val1: "36.74", val2: "" },
            { id: 9, name: "Bharatpur", val1: "25.49", val2: "" },
            { id: 10, name: "Sikar", val1: "26.77", val2: "" },
        ],
        tasks: [
            { id: 1, text: "Task 1: Copy district names to column C", marks: 2 },
            { id: 2, text: "Task 2: Copy population data to column D", marks: 2 },
            { id: 3, text: "Task 3: Total population: =SUM(D2:D10) in D11", marks: 2 },
            { id: 4, text: "Task 4: Average population: =AVERAGE(D2:D10) in D12", marks: 2 },
            { id: 5, text: "Task 5: Most populated: =MAX(D2:D10) in D13", marks: 2 },
            { id: 6, text: "Task 6: Least populated: =MIN(D2:D10) in D14", marks: 2 },
            { id: 7, text: "Task 7: District count: =COUNT(D2:D10) in D15", marks: 2 },
            { id: 8, text: "Task 8: Jaipur percentage: =(D2/D11)*100 in E2", marks: 2 },
            { id: 9, text: "Task 9: Sort data by population (descending)", marks: 2 },
            { id: 10, text: "Task 10: Add decimal formatting (2 places)", marks: 2 },
        ]
    },
    {
        id: 10,
        title: "Test 10: Quarterly Sales Target",
        type: 'Excel',
        instructions: "Calculate quarterly performance and target achievement",
        data: [
            { id: 1, name: "Quarter", val1: "Sales (Crores)", val2: "" },
            { id: 2, name: "Q1-2024", val1: "45.5", val2: "" },
            { id: 3, name: "Q2-2024", val1: "52.3", val2: "" },
            { id: 4, name: "Q3-2024", val1: "48.7", val2: "" },
            { id: 5, name: "Q4-2024", val1: "61.2", val2: "" },
            { id: 6, name: "Q1-2025", val1: "55.8", val2: "" },
            { id: 7, name: "Q2-2025", val1: "58.9", val2: "" },
            { id: 8, name: "Q3-2025", val1: "63.4", val2: "" },
            { id: 9, name: "Q4-2025", val1: "70.1", val2: "" },
            { id: 10, name: "Q1-2026", val1: "67.5", val2: "" },
        ],
        tasks: [
            { id: 1, text: "Task 1: Enter quarter names in column C", marks: 2 },
            { id: 2, text: "Task 2: Enter sales figures in column D", marks: 2 },
            { id: 3, text: "Task 3: Total sales: =SUM(D2:D10) in D11", marks: 2 },
            { id: 4, text: "Task 4: Average quarterly sales: =AVERAGE(D2:D10) in D12", marks: 2 },
            { id: 5, text: "Task 5: Peak sales: =MAX(D2:D10) in D13", marks: 2 },
            { id: 6, text: "Task 6: Lowest sales: =MIN(D2:D10) in D14", marks: 2 },
            { id: 7, text: "Task 7: Quarter count: =COUNT(D2:D10) in D15", marks: 2 },
            { id: 8, text: "Task 8: Q4-2025 share: =(D9/D11)*100 in E9", marks: 2 },
            { id: 9, text: "Task 9: Apply gradient fill to headers", marks: 2 },
            { id: 10, text: "Task 10: Insert column chart for visualization", marks: 2 },
        ]
    }
];

export const INITIAL_CPT_WORD = [
    {
        id: 1,
        title: "Test 1: Basic Formatting",
        type: 'Word',
        isFree: true,
        content: `<p>Rajasthan Staff Selection Board conducts various examinations for recruitment.</p><p>The board ensures fair and transparent selection process for all candidates.</p><p>Computer proficiency test is an essential part of the examination.</p><p>Candidates must demonstrate their typing and formatting skills effectively.</p>`,
        questions: [
            { id: 1, text: "Document ke pehle paragraph ka Font Size 14 pt karein", marks: 2 },
            { id: 2, text: "Dusre paragraph ko 'Bold' aur 'Italic' kijiye", marks: 2 },
            { id: 3, text: "Teesre paragraph ka alignment 'Center' karein", marks: 2 },
            { id: 4, text: "Word 'Rajasthan' ko 'Highlight' karein (Yellow)", marks: 2 },
            { id: 5, text: "Fourth paragraph ko 'Right Align' karein", marks: 2 },
            { id: 6, text: "Pehle word ko 'Double Underline' kijiye", marks: 2 },
            { id: 7, text: "Sabhi paragraphs ki Line Spacing 1.15 set karein", marks: 2 },
            { id: 8, text: "Word 'Computer' ka font color Blue karein", marks: 2 },
            { id: 9, text: "Header mein 'LDC Exam 2024' likhein", marks: 2 },
            { id: 10, text: "Footer mein 'Page Number' insert karein", marks: 2 },
        ]
    },
    {
        id: 2,
        title: "Test 2: Table & Layout",
        type: 'Word',
        content: `<p>Government offices require proper documentation skills from employees.</p><p>Table creation is an important skill for office work.</p><p>Formatting data in tables makes information more readable.</p>`,
        questions: [
            { id: 1, text: "Ek 3x3 Table insert karein", marks: 2 },
            { id: 2, text: "Table ki pehli row ko 'Merge' karke usmein 'Monthly Report' likhein", marks: 2 },
            { id: 3, text: "Table ke cells mein 'Shading' (Light Grey color) bharein", marks: 2 },
            { id: 4, text: "Page Orientation ko 'Landscape' karein", marks: 2 },
            { id: 5, text: "Pehle paragraph ka Font Style 'Arial' karein", marks: 2 },
            { id: 6, text: "Poore document par 'Page Border' (Box style) lagayein", marks: 2 },
            { id: 7, text: "Page Size 'A4' select karein", marks: 2 },
            { id: 8, text: "Page Margin ko 'Normal' set karein", marks: 2 },
            { id: 9, text: "Document mein 'Watermark' (Text: 'Draft') lagayein", marks: 2 },
            { id: 10, text: "Table ka border thickness 1.5 pt karein", marks: 2 },
        ]
    },
    {
        id: 3,
        title: "Test 3: Advanced Formatting",
        type: 'Word',
        content: `<p>Professional document preparation requires attention to detail.</p><p>H2SO4 is the chemical formula for sulfuric acid.</p><p>The area of circle is πr2 where r is radius.</p><p>Proper formatting enhances document readability significantly.</p>`,
        questions: [
            { id: 1, text: "Pehle paragraph ko 'Justify Align' karein", marks: 2 },
            { id: 2, text: "'H2SO4' mein '2' aur '4' ko Subscript karein", marks: 2 },
            { id: 3, text: "'πr2' mein '2' ko Superscript karein", marks: 2 },
            { id: 4, text: "Font Size poore document ka 12 pt karein", marks: 2 },
            { id: 5, text: "Word 'Professional' ko Bold aur Red color karein", marks: 2 },
            { id: 6, text: "Teesre paragraph ka background color Light Yellow karein", marks: 2 },
            { id: 7, text: "Document ka title 'CPT Exam' header mein add karein", marks: 2 },
            { id: 8, text: "Paragraph spacing Before: 6 pt set karein", marks: 2 },
            { id: 9, text: "Word 'significantly' ko Italic aur Underline karein", marks: 2 },
            { id: 10, text: "Footer mein current date insert karein", marks: 2 },
        ]
    },
    {
        id: 4,
        title: "Test 4: Hindi Document Formatting",
        type: 'Word',
        content: `<p>भारत सरकार के कार्यालयों में हिंदी का प्रयोग अनिवार्य है।</p><p>कंप्यूटर पर हिंदी टाइपिंग एक महत्वपूर्ण कौशल है।</p><p>राजस्थान में सरकारी परीक्षाओं का आयोजन नियमित रूप से होता है।</p>`,
        questions: [
            { id: 1, text: "Pehle paragraph ka Font 'Mangal' karein", marks: 2 },
            { id: 2, text: "Word 'भारत सरकार' ko Bold karein", marks: 2 },
            { id: 3, text: "Dusre paragraph ka Font Size 14 pt karein", marks: 2 },
            { id: 4, text: "Teesre paragraph ko Center Align karein", marks: 2 },
            { id: 5, text: "Word 'राजस्थान' ko Highlight (Yellow) karein", marks: 2 },
            { id: 6, text: "Pehle paragraph ko Justify Align karein", marks: 2 },
            { id: 7, text: "Line Spacing poore document ki 1.5 karein", marks: 2 },
            { id: 8, text: "Header mein 'एलडीसी परीक्षा 2024' likhein", marks: 2 },
            { id: 9, text: "Word 'कंप्यूटर' ka color Blue karein", marks: 2 },
            { id: 10, text: "Footer mein page number Hindi mein insert karein", marks: 2 },
        ]
    },
    {
        id: 5,
        title: "Test 5: Office Documentation",
        type: 'Word',
        content: `<p>To,</p><p>The Office Superintendent,</p><p>District Administrative Office,</p><p>Jaipur, Rajasthan.</p><p>Subject: Request for leave approval</p><p>Sir, I request you to kindly grant me leave for three days.</p><p>Thanking you,</p><p>Your obedient,</p><p>Employee Name</p>`,
        questions: [
            { id: 1, text: "'The Office Superintendent' ko Bold karein", marks: 2 },
            { id: 2, text: "Subject line ko Center Align aur Underline karein", marks: 2 },
            { id: 3, text: "'Jaipur, Rajasthan' ka font color Red karein", marks: 2 },
            { id: 4, text: "Last three lines ko Right Align karein", marks: 2 },
            { id: 5, text: "Word 'leave' ko Highlight karein", marks: 2 },
            { id: 6, text: "Pehle paragraph ka Font Size 11 pt karein", marks: 2 },
            { id: 7, text: "Poore document ka Line Spacing 1.15 karein", marks: 2 },
            { id: 8, text: "Header mein 'Official Letter' likhein", marks: 2 },
            { id: 9, text: "Page Border (Shadow style) lagayein", marks: 2 },
            { id: 10, text: "Footer mein date aur page number daalein", marks: 2 },
        ]
    },
    {
        id: 6,
        title: "Test 6: Report Formatting",
        type: 'Word',
        content: `<p>ANNUAL REPORT 2024</p><p>Department Performance Analysis</p><p>The department achieved 95% target completion rate.</p><p>Total Budget: Rs. 50,00,000</p><p>Expenditure: Rs. 47,50,000</p><p>Savings: Rs. 2,50,000</p>`,
        questions: [
            { id: 1, text: "First line 'ANNUAL REPORT 2024' ko Center Align aur Bold karein", marks: 2 },
            { id: 2, text: "First line ka Font Size 16 pt karein", marks: 2 },
            { id: 3, text: "Second line ko Bold aur Italic karein", marks: 2 },
            { id: 4, text: "Number '95%' ko Highlight (Green) karein", marks: 2 },
            { id: 5, text: "Last three lines ko Bullet Points mein convert karein", marks: 2 },
            { id: 6, text: "Word 'REPORT' ka font color Blue karein", marks: 2 },
            { id: 7, text: "Poore document ka Font 'Calibri' karein", marks: 2 },
            { id: 8, text: "Watermark 'Confidential' add karein", marks: 2 },
            { id: 9, text: "Header mein company logo ke liye space reserve karein", marks: 2 },
            { id: 10, text: "Footer mein 'Page X of Y' format mein page number", marks: 2 },
        ]
    },
    {
        id: 7,
        title: "Test 7: Notice & Circular",
        type: 'Word',
        content: `<p>NOTICE</p><p>Date: 15/January/2024</p><p>All employees are hereby informed that office timings have been revised.</p><p>New Timings: 9:00 AM to 5:30 PM</p><p>Effective from: 01/February/2024</p><p>Secretary</p><p>Administration Department</p>`,
        questions: [
            { id: 1, text: "'NOTICE' ko Center Align, Bold aur Underline karein", marks: 2 },
            { id: 2, text: "'NOTICE' ka Font Size 18 pt karein", marks: 2 },
            { id: 3, text: "Date line ko Right Align karein", marks: 2 },
            { id: 4, text: "'New Timings' line ko Bold aur Italic karein", marks: 2 },
            { id: 5, text: "Word 'revised' ko Highlight (Yellow) karein", marks: 2 },
            { id: 6, text: "Last two lines ko Right Align karein", marks: 2 },
            { id: 7, text: "Poore document ka Line Spacing 1.5 karein", marks: 2 },
            { id: 8, text: "Page Border (Double line) lagayein", marks: 2 },
            { id: 9, text: "Header mein 'Government of Rajasthan' likhein", marks: 2 },
            { id: 10, text: "Footer mein department contact details ke liye field", marks: 2 },
        ]
    },
    {
        id: 8,
        title: "Test 8: Technical Document",
        type: 'Word',
        content: `<p>Technical Specifications Document</p><p>System Requirements: Windows 10 or above</p><p>RAM: Minimum 4GB (8GB recommended)</p><p>Storage: 500GB HDD or 256GB SSD</p><p>Software: MS Office 2016 or later</p><p>Network: Broadband connection required</p>`,
        questions: [
            { id: 1, text: "Title ko Center Align aur Bold karein", marks: 2 },
            { id: 2, text: "Title ka Font Size 14 pt aur color Dark Blue karein", marks: 2 },
            { id: 3, text: "All requirement lines ko Numbered List mein convert karein", marks: 2 },
            { id: 4, text: "'4GB' aur '8GB' ko Bold karein", marks: 2 },
            { id: 5, text: "Word 'recommended' ko Italic karein", marks: 2 },
            { id: 6, text: "Ek 2x5 table banayein requirements ke liye", marks: 2 },
            { id: 7, text: "Poore document ka Font 'Times New Roman' karein", marks: 2 },
            { id: 8, text: "Header mein 'Technical Documentation' likhein", marks: 2 },
            { id: 9, text: "Page Margin ko 'Narrow' set karein", marks: 2 },
            { id: 10, text: "Footer mein 'Version 1.0' aur date add karein", marks: 2 },
        ]
    },
    {
        id: 9,
        title: "Test 9: Meeting Minutes",
        type: 'Word',
        content: `<p>MEETING MINUTES</p><p>Date: 10/Dec/2023 | Time: 10:00 AM | Venue: Conference Room</p><p>Attendees: Mr. Sharma, Ms. Patel, Dr. Kumar</p><p>Agenda: Discussion on quarterly targets and budget allocation</p><p>Decisions: Budget increased by 15% for next quarter</p><p>Action Items: Submit revised proposals by 20/Dec/2023</p>`,
        questions: [
            { id: 1, text: "'MEETING MINUTES' ko Center, Bold aur Underline karein", marks: 2 },
            { id: 2, text: "Second line mein '|' ke saath data ko table format mein arrange karein", marks: 2 },
            { id: 3, text: "All headings (Attendees, Agenda, etc.) ko Bold karein", marks: 2 },
            { id: 4, text: "'15%' ko Highlight (Green) karein", marks: 2 },
            { id: 5, text: "Names (Mr. Sharma, etc.) ko Italic karein", marks: 2 },
            { id: 6, text: "Date '20/Dec/2023' ko Bold aur Red color karein", marks: 2 },
            { id: 7, text: "Poore document ka Line Spacing Double (2.0) karein", marks: 2 },
            { id: 8, text: "Header mein organization name ke liye space", marks: 2 },
            { id: 9, text: "Footer mein 'Confidential - Internal Use Only' likhein", marks: 2 },
            { id: 10, text: "Page Border (3D effect) lagayein", marks: 2 },
        ]
    },
    {
        id: 10,
        title: "Test 10: Certificate Format",
        type: 'Word',
        content: `<p>CERTIFICATE OF APPRECIATION</p><p>This is to certify that</p><p>Mr./Ms. [Name]</p><p>has successfully completed the Computer Proficiency Training Program</p><p>conducted by Rajasthan Skill Development Center</p><p>Date of Completion: ___________</p><p>Authorized Signature: ___________</p>`,
        questions: [
            { id: 1, text: "'CERTIFICATE OF APPRECIATION' ko Center, Bold karein", marks: 2 },
            { id: 2, text: "Title ka Font Size 20 pt aur color Dark Green karein", marks: 2 },
            { id: 3, text: "All text ko Center Align karein", marks: 2 },
            { id: 4, text: "'Mr./Ms. [Name]' ka Font Size 16 pt karein", marks: 2 },
            { id: 5, text: "Word 'successfully' ko Bold aur Italic karein", marks: 2 },
            { id: 6, text: "'Rajasthan Skill Development Center' ko Underline karein", marks: 2 },
            { id: 7, text: "Poore document ka Line Spacing 1.5 karein", marks: 2 },
            { id: 8, text: "Decorative Page Border (Art style) lagayein", marks: 2 },
            { id: 9, text: "Watermark 'Original' add karein", marks: 2 },
            { id: 10, text: "Footer mein certificate number field add karein", marks: 2 },
        ]
    }
];
